#!/bin/bash

echo "=========================================="
echo "WordPress MySQL Database Setup"
echo "=========================================="
echo ""
echo "Please run these commands manually:"
echo ""
echo "# 1. Start MySQL"
echo "sudo systemctl start mysql"
echo ""
echo "# 2. Create database and user"
echo "sudo mysql << 'EOF'"
echo "CREATE DATABASE IF NOT EXISTS wordpress_db CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;"
echo "CREATE USER IF NOT EXISTS 'wordpress_user'@'localhost' IDENTIFIED BY 'wordpress_password_123';"
echo "GRANT ALL PRIVILEGES ON wordpress_db.* TO 'wordpress_user'@'localhost';"
echo "FLUSH PRIVILEGES;"
echo "SELECT 'Database created successfully!' AS Status;"
echo "EXIT;"
echo "EOF"
echo ""
echo "# 3. Install phpMyAdmin (optional)"
echo "sudo apt install phpmyadmin -y"
echo "ln -s /usr/share/phpmyadmin /home/saiful/wordpress/phpmyadmin"
echo ""
echo "=========================================="
echo ""

